version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./php/Dockerfile
      args:
          USER_ID: ${USER_ID}
          GROUP_ID: ${GROUP_ID}
    container_name: panterest_web
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - .:/var/www/html/panterest/
    restart: always
    ports:
      - "8741:80"
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panterest_web.rule=Host(`panterest.docker.localhost`)"
      - "traefik.http.routers.panterest_web.tls=true"
    networks:
      - proxy
    hostname: panterest.docker.localhost

  db:
    image: mysql:5.7
    container_name: panterest_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3307:3306"
    networks:
      - proxy

  phpmyadmin:
    image: phpmyadmin
    container_name: panterest_phpmyadmin
    links:
      - db
    restart: always
    ports:
      - "8089:80"
    security_opt:
      - no-new-privileges:true
    environment:
      PMA_HOST: db
      MEMORY_LIMIT: -1
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panterest_phpmyadmin.rule=Host(`pma-panterest.docker.localhost`)"
      - "traefik.http.routers.panterest_phpmyadmin.tls=true"
    networks:
      - proxy
    hostname: pma-panterest.docker.localhost

  maildev:
    image: maildev/maildev
    container_name: panterest_maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    restart: always
    ports:
      - "8081:80"
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panterest_maildev.rule=Host(`maildev-panterest.docker.localhost`)"
      - "traefik.http.routers.panterest_maildev.tls=true"
    networks:
        - proxy
    hostname: maildev-panterest.docker.localhost

networks:
  proxy:
    external: true

volumes:
  db_data: